# Generated by Django 5.0.1 on 2024-02-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
    ]
