# Generated by Django 4.1.2 on 2024-04-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-user']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
